### ISSUE TITLE
testing

### ISSUE THREAD

**Issue by FatimaaIsmail27** [Qsingle/LearnablePromptSAM#11]
How can I test the model after training ?

**Comment by pkyzh2006** [comment]
same, how can I get the result via trained model?

**Comment by Qsingle** [comment]
Hello, we release the DPT at the repository [imed_vision](https://github.com/Qsingle/imed_vision) and we provide the training example and evaluation example at the repository. Hope this can help you. The learnable SAM is also added to the repository. You can use the following code to import it to the evaluation code.

```python
from models.segmentation.learnable_sam import PromptSAM
```

**Comment by Qsingle** [comment]
The learnable SAM is also added to the repository. You can use the following code to import it to the evaluation code.

**Comment by FatimaaIsmail27** [comment]
this issue is closed.
